# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- trunk

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ArtifactoryDocker@1
  displayName: Docker Push
  inputs:
    command: 'push'
    repository: 'devops/devsecops-engine-tools'
    artifactoryService: 'Artifactor'
    targetRepo: 'docker-registry'
    imageName: 'artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(version)'