check:
- CKV_DOCKER_1
- CKV_DOCKER_2
- CKV_DOCKER_3
- CKV_DOCKER_4
- CKV_DOCKER_5
- CKV_DOCKER_6
- CKV_DOCKER_7
- CKV_DOCKER_8
- CKV_DOCKER_9
- CKV_DOCKER_10
- CKV_DOCKER_11
- CKV2_DOCKER_1
compact: true
directory: C:/Users/cesospin/Documents/dev/NU0051001_Engagement_Services_MR/ds_ms_alias_identity/
evaluate-variables: true
output: json
quiet: true
soft-fail: false
