# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - trunk
      - feature/*
      - fix/*

  pull_request:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  unit-tests:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.10"]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv==2022.10.4
      - name: Install dependencies
        run: |
          
      - uses: imranismail/setup-kustomize@v1
      - name: Unit tests
        run: |
          pipenv run python -m pytest --cov=rules tests

         
