name: Deploy

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools virtualenv wheel
          python -m virtualenv _venv
          source _venv/bin/activate
          python -m pip install -r requirements.txt
          python setup.py bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tools/dist/
          repository-url: https://pypi.org/p/devsecops-engine-tools
          password: ${{ secrets.PDN_PYPI_API_TOKEN }}
