name: Deploy

on:
  push:
    branches:
      - feature/*

jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write

  #   steps:
  #     - name: Download the distribution packages
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: python-package-distributions
  #         path: tools/dist/

  #     - name: Publish a Python distribution to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         packages-dir: tools/dist/
  #         repository-url: https://pypi.org/p/devsecops-engine-tools
  #         password: ${{ secrets.PDN_PYPI_API_TOKEN }}

  create_tag:
    # needs:
    #   - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create new tag ${{ github.event.inputs.release_number }}
        run: |
          VERSION=$(grep -E "version" tools/devsecops_engine_tools/version.py | cut -d= -f2 | sed "s/[[:space:]']//g")
          NEW_TAG="v$VERSION"
          echo "New Tag: $NEW_TAG"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a $NEW_TAG -m "[bot] release $NEW_TAG"
      - name: Push tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSHSECRET }}
          tags: true
