name: Release

on:
  push:
    tags:
    - 'v*'

jobs:

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: tools/dist/

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tools/dist/

  deploy_dockerhub:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from version.py
        id: get-version
        run: |
          VERSION=$(grep -E "version" tools/devsecops_engine_tools/version.py | cut -d= -f2 | sed "s/[[:space:]']//g")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build --build-arg VERSION=${{ env.VERSION }} -t bancolombia/devsecops-engine-tools:${{ env.VERSION }} -f docker/Dockerfile .
          docker tag bancolombia/devsecops-engine-tools:${{ env.VERSION }} bancolombia/devsecops-engine-tools:${{ env.VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Publish a Docker image to Dockerhub
        run: |
          docker image push bancolombia/devsecops-engine-tools:${{ env.VERSION }}